[package]
name = "autofarm-editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
autofarm-ai.workspace = true
autofarm-sim.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
